### ISSUE TITLE
CI build broken

### ISSUE THREAD

**Issue by vorburger** [MariaDB4j/MariaDB4j#1045]
The `main` branch, and all (e.g. dependabot) PRs build on CI is currently broken due to:

```
Caused by: ch.vorburger.exec.ManagedProcessException: Program [/tmp/MariaDB4j/base/bin/mariadb, --default-character-set=utf8, --socket=/tmp/MariaDB4j.39105.sock] (in working directory /tmp/MariaDB4j/base) failed with Exception: , last 100 lines of console:
/tmp/MariaDB4j/base/bin/mariadb: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:345)
	at ch.vorburger.exec.ManagedProcess.startExecute(ManagedProcess.java:247)
	at ch.vorburger.exec.ManagedProcess.start(ManagedProcess.java:186)
	at ch.vorburger.mariadb4j.DB.run(DB.java:370)
	... 27 more
```

**Comment by vorburger** [comment]
As per the `README`, installing `libncurses5` normally fixes this...

.... but the CI [does that](https://github.com/MariaDB4j/MariaDB4j/blob/36f291e05187c7a52db51618e416136d66119169/.github/workflows/test.yaml#L30) (since a long time) - but for some reason that recently stopped working.

Attempted solutions:

1. #1043 `execute_install_scripts: true` - does not help
1. #1044 apt install libncurses5 without cache-apt-pkgs-action - TBD
1. #1046 Ubuntu 22.04 instead of latest 24.04 - TBD

**Comment by vorburger** [comment]
#1046 is good enough for today.

Medium term we should perhaps some other figure out how to get this working on 24.04 ...

... is anyone reading along here interested in digging further into this to try to find a solution?

**Comment by r-roos** [comment]
It seems the mariadb binaries require libncurses5. I managed to apply the following workaround to make it work with the libncurses6 libraries:
1. Install libncurses6 via `apt-get update -y && apt-get install -y libncurses6`
2. Symlink the libncurses6 libs to libncurses5 via (directories may vary between linux distributions, double check if they are correct for your distribution)
```
 ln -s "/usr/lib/x86_64-linux-gnu/libncurses.so.6.4" "/usr/lib/x86_64-linux-gnu/libncurses.so.5"
 ln -s "/usr/lib/x86_64-linux-gnu/libtinfo.so.6.4" "/usr/lib/x86_64-linux-gnu/libtinfo.so.5"
```

**Comment by vorburger** [comment]
#1120 is related to and follows-up on this problem, and will (when resolved) should (TBC) allow us to use 24.04 instead of 22.04.

**Comment by vorburger** [comment]
With #1122 (from #1074), I'm now considering this done.
